### ISSUE TITLE
Extend logic to include cooling

### ISSUE THREAD

**Issue by momipsl** [QZabre/qcc-001-mc#1]
The instrument logic can be extended so as to control cooling devices.  Gabriel will supply logic definition.

**Comment by momipsl** [comment]
The following 2 emails from Gabriel sum up the requirements which will be implemented in 2 steps:


# Step 1 - simple

- pin 11 are the fans, pin 12 is the waterpump
- default: fans at 50%, pump at 50% (we can also try 30%)
- Amplifier temperature > 30 deg C: fans at 100%, pump at 100%



# Step 2 - proportional


- it seems that we would want a 25 kHz pwm signal. the board should be able to output this.

-  would a simple proportional controller would be easy to implement?
idle: < 25 deg C: fans and pump at 20%
linear: 20% more per degree above 25 deg C.
update in normal loop speed.

**Comment by QZabre-Gabriel** [comment]
Turns out that pins 11 and 12 are only tachometers.
pwm is on pin 10, 10kHz using pulseio
fan = pulseio.PWMOut(board.D10,duty_cycle=0x8fff,frequency=10000)
lowest running pump is 0x8fff as duty cycle

**Comment by QZabre-Gabriel** [comment]
sorry, that's 0x6fff.

**Comment by QZabre-Gabriel** [comment]
And the pwm does not work in combination with busio :-(
